from __future__ import annotations

import asyncio
import json
from uuid import uuid4

from social_ingestion_mcp.adapters.bitable_adapter import FeishuBitableAdapter
from social_ingestion_mcp.config import AppConfig
from social_ingestion_mcp.errors import SocialIngestionError
from social_ingestion_mcp.models import BitableWritePayload, Platform


async def amain() -> int:
    config = AppConfig.model_validate({**AppConfig().model_dump(), "feishu_bitable_force_write": True})
    adapter = FeishuBitableAdapter(config)
    job_id = f"bitable-validation-{uuid4().hex[:12]}"
    try:
        record_id = await adapter.upsert_record(
            BitableWritePayload(
                job_id=job_id,
                platform=Platform.XHS,
                source_url="https://example.invalid/bitable-validation",
                source_title="Bitable Validation Record",
                cleaned_text="This is a real Feishu Bitable validation write generated by the local project.",
                transcript_text="Validation transcript.",
                metadata={
                    "media_path": "",
                    "source_message_id": "",
                    "validation": True,
                    "note": "Created by scripts/test_bitable_write.py",
                },
            )
        )
    except SocialIngestionError as exc:
        print(
            json.dumps(
                {
                    "ok": False,
                    "job_id": job_id,
                    "table_id": FeishuBitableAdapter._normalize_table_id(config.feishu_bitable_table_id),
                    "error_code": exc.code,
                    "error_message": str(exc),
                },
                ensure_ascii=False,
                indent=2,
            )
        )
        return 1

    print(
        json.dumps(
            {
                "ok": True,
                "job_id": job_id,
                "record_id": record_id,
                "table_id": FeishuBitableAdapter._normalize_table_id(config.feishu_bitable_table_id),
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(amain()))